version: '3.8'

services:
  django:
    build:
      context: .
      target: development
    command: python -m django runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "9001:8000"
    env_file:
      - .env.dev
    environment:
      - DJANGO_ENV=development
      - PYTHONPATH=/app
      - DJANGO_SETTINGS_MODULE=settings
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:17.4
    volumes:
      - ledgerflow_postgres_data_dev:/var/lib/postgresql/data
    env_file:
      - .env.dev
    ports:
      - "5435:5432"

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - ledgerflow_redis_data_dev:/data

  adminer:
    image: adminer
    ports:
      - "8082:8080"
    depends_on:
      - postgres

volumes:
  ledgerflow_postgres_data_dev:
  ledgerflow_redis_data_dev: 